# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvHBZrQeCZWggBlVUxeDUbQauecNnWoX
"""

import pandas as pd

# Lendo arquivo excel via Pandas
df = pd.read_excel('./alunos.xlsx')

df

# Lendo apenas as duas primeiras linhas do excel
df.head(2)

# Dropando colunas
df = df.drop(columns=['Nota1', 'Nota2', 'Nota3'])

df.head(2)

df

# Realizando filtro de um dado numa determinada coluna
df.loc[df['Nome'] == 'Lucas Oliveira']

# Realizando o mesmo filtro feito acima, porém, exibindo apenas a coluna CPF
df.loc[df['Nome'] == 'Lucas Oliveira', ['CPF']]