# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvHBZrQeCZWggBlVUxeDUbQauecNnWoX
"""

import pandas as pd

# Lendo arquivo excel via Pandas
df = pd.read_excel('./alunos.xlsx')

df

# Lendo apenas as duas primeiras linhas do excel
df.head(2)

# Dropando colunas
df = df.drop(columns=['Nota1', 'Nota2', 'Nota3'])

df.head(2)

df

# Realizando filtro de um dado numa determinada coluna
df.loc[df['Nome'] == 'Lucas Oliveira']

# Realizando o mesmo filtro feito acima, porém, exibindo apenas a coluna CPF
df.loc[df['Nome'] == 'Lucas Oliveira', ['Nome', 'CPF']]

df

# Agrupar os dados iguais de uma determina colunas, somando as demais colunas em função do agrupamento
df.groupby(['Série']).sum()

df

# Recriando as colunas de notas que haviam sido dropadas acima, porém, replicando os mesmos valores para a determinada coluna
df = df.assign(Nota1=9, Nota2=10, Nota3=8)
df

# Alterando valores nas colunas Notas
df['Nota1'] = [2, 5, 4, 10, 5, 8, 1, 9, 0, 2]
df['Nota2'] = [9, 10, 8, 0, 10, 6, 2, 3, 4, 5]
df['Nota3'] = [6, 3, 7, 1, 8, 3, 10, 4, 6, 5]
df
